# Library Management Analysis

A local library wants to better understand how its books are being borrowed. You are given a dataset containing information about books, members, and borrowing records. Your task is to analyze the dataset and produce useful insights that could help the library improve its services.

### Requirements

* Create a GitHub repository for the project and use Git throughout your development with meaningful commits.
* Include a `README.md` explaining the project, dataset, and how to run your code.
* Write clean, readable Python code and use functions whenever appropriate.
* Load the dataset using Pandas.
* Explore the dataset by displaying enough information to understand its structure before beginning the analysis.
* If the dataset contains any issues that prevent your analysis from running correctly, make only the minimum changes required to continue. You are not expected to perform a complete data cleaning process.
* Calculate the probability of randomly selecting:

  * A borrowed book from a specific genre.
  * A member belonging to a specific membership type.
  * A borrowing record that satisfies two conditions of your choice.
* Using Pandas, answer the following:

  * Find the category with the highest and lowest number of borrowings.
  * Determine which members borrow books most frequently.
  * Compare borrowing activity between different membership types.
  * Analyze how borrowing changes across publication years.
  * Identify the most popular authors.
  * Find the books that have never been borrowed.
  * Compare the average borrowing duration across genres.
  * Show the distribution of books across genres.
  * Analyze monthly borrowing trends (if borrowing dates are available).
  * Present three additional insights of your choice.
* Using NumPy, answer the following:

  * Convert one or more numerical columns into NumPy arrays.
  * Identify the highest and lowest values in a numerical column.
  * Use boolean indexing to filter a subset of the data.
  * Sort a NumPy array and display the result.
  * Perform at least one vectorized calculation to create a new numerical result or metric.
* Produce a final summary highlighting the most important insights from your analysis.

Your project should be well-structured and reproducible. Anyone running your code should be able to obtain the same results without modifying the source code.

In [55]:
import pandas as pd
import numpy as np

In [56]:
from google.colab import files

uploaded = files.upload()

Saving books.csv to books (1).csv
Saving borrowings.csv to borrowings (1).csv
Saving members.csv to members (1).csv

In [57]:
book = pd.read_csv('books.csv')
book.head()

,BookID,Title,Author,Genre,PublicationYear,Publisher,Pages,Language,CopiesAvailable
0,B001,Book 1,George Orwell,Science Fiction,1986,Pearson,401,English,3
1,B002,Book 2,Brandon Sanderson,Mystery,1991,Pearson,678,English,1
2,B003,Book 3,Jane Austen,Programming,1987,Penguin,215,English,3
3,B004,Book 4,Brandon Sanderson,Business,2023,Penguin,694,English,3
4,B005,Book 5,Mark Lee,Business,2011,HarperCollins,579,English,4

In [58]:
borrowings = pd.read_csv('borrowings.csv')
borrowings.head()

  BorrowID MemberID BookID  BorrowDate  ReturnDate
0   BR0001     M063   B143  2025-05-17  2025-06-07
1   BR0002     M101   B159  2024-10-14  2024-11-12
2   BR0003     M140   B077  2025-07-31  2025-08-09
3   BR0004     M007   B385  2026-02-25  2026-03-17
4   BR0005     M054   B184  2025-04-17  2025-05-12

In [59]:
members = pd.read_csv('members.csv')
members.head()

  MemberID      Name MembershipType  Age  Gender    JoinDate
0     M001  Member 1        Student   47    Male  2025-02-18
1     M002  Member 2         Public   47  Female  2022-02-14
2     M003  Member 3         Public   43  Female  2022-01-07
3     M004  Member 4        Student   65    Male  2025-03-30
4     M005  Member 5        Student   22    Male  2024-05-17

In [60]:
members.isnull().sum()

MemberID          0
Name              0
MembershipType    0
Age               0
Gender            0
JoinDate          0
dtype: int64

In [61]:

borrowings.isnull().sum()

BorrowID      0
MemberID      0
BookID        0
BorrowDate    0
ReturnDate    0
dtype: int64

In [62]:
book.isnull().sum()

BookID             0
Title              0
Author             0
Genre              0
PublicationYear    0
Publisher          0
Pages              0
Language           0
CopiesAvailable    0
dtype: int64

In [63]:
print(members.shape)
print(borrowings.shape)
print(book.shape)

(150, 6)
(2000, 5)
(400, 9)

In [64]:
print(members.info())
print(borrowings.info())
print(book.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   MemberID        150 non-null    object
 1   Name            150 non-null    object
 2   MembershipType  150 non-null    object
 3   Age             150 non-null    int64
 4   Gender          150 non-null    object
 5   JoinDate        150 non-null    object
dtypes: int64(1), object(5)
memory usage: 7.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   BorrowID    2000 non-null   object
 1   MemberID    2000 non-null   object
 2   BookID      2000 non-null   object
 3   BorrowDate  2000 non-null   object
 4   ReturnDate  2000 non-null   object
dtypes: object(5)
memory usage: 78.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   BookID           400 non-null    object
 1   Title            400 non-null    object
 2   Author           400 non-null    object
 3   Genre            400 non-null    object
 4   PublicationYear  400 non-null    int64
 5   Publisher        400 non-null    object
 6   Pages            400 non-null    int64
 7   Language         400 non-null    object
 8   CopiesAvailable  400 non-null    int64
dtypes: int64(3), object(6)
memory usage: 28.3+ KB
None

In [65]:
print(book.duplicated().sum)
print(members.duplicated().sum)
print(borrowings.duplicated().sum)

<bound method Series.sum of 0      False
1      False
2      False
3      False
4      False
       ...
395    False
396    False
397    False
398    False
399    False
Length: 400, dtype: bool>
<bound method Series.sum of 0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool>
<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool>

In [66]:
data_set = pd.merge(book, borrowings, on='BookID')
data_set = pd.merge(data_set, members, on='MemberID')

In [67]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   BookID           2000 non-null   object
 1   Title            2000 non-null   object
 2   Author           2000 non-null   object
 3   Genre            2000 non-null   object
 4   PublicationYear  2000 non-null   int64
 5   Publisher        2000 non-null   object
 6   Pages            2000 non-null   int64
 7   Language         2000 non-null   object
 8   CopiesAvailable  2000 non-null   int64
 9   BorrowID         2000 non-null   object
 10  MemberID         2000 non-null   object
 11  BorrowDate       2000 non-null   object
 12  ReturnDate       2000 non-null   object
 13  Name             2000 non-null   object
 14  MembershipType   2000 non-null   object
 15  Age              2000 non-null   int64
 16  Gender           2000 non-null   object
 17  JoinDate         2000 non-null   object
dtypes: int64(4), object(14)
memory usage: 281.4+ KB

In [68]:
data_set["Genre"].unique()

array(['Science Fiction', 'Mystery', 'Programming', 'Business', 'Fantasy',
       'Data Science', 'History', 'Self Help', 'Romance', 'Biography'],
      dtype=object)

In [69]:
genre = "History"
prob_genre = (data_set["Genre"] == genre).mean()
print(f"Probability is {genre} book: {prob_genre:.2f}")

Probability is History book: 0.04

In [70]:
data_set["MembershipType"].unique()

array(['Student', 'Faculty', 'Premium', 'Public'], dtype=object)

In [71]:
membership = "Public"

prob_member = (data_set["MembershipType"] == membership).mean()

print(f"Probability : {membership} member: {prob_member:.2f}")

Probability : Public member: 0.21

In [72]:
prob_two_conditions = (
    (
        (data_set["Genre"] == "Science Fiction") &
        (data_set["MembershipType"] == "Premium")
    ).mean()
)

print(f"Probability of Science Fiction book borrowed by a Premium member: {prob_two_conditions:.2f}")

Probability of Science Fiction book borrowed by a Premium member: 0.00

In [73]:
prob_two_conditions = (
    (
        (data_set["Genre"] == "History") &
        (data_set["MembershipType"] == "Public")
    ).mean()
)
print(f"Probability : {prob_two_conditions:.2f}")

Probability : 0.01

In [74]:
genre_count = data_set["Genre"].value_counts()

genre_count

Genre
Mystery            512
Data Science       328
Fantasy            316
Programming        295
Business           121
Self Help           97
Biography           84
Science Fiction     83
History             83
Romance             81
Name: count, dtype: int64

In [75]:
print("Highest Category:")
print(genre_count.index[0], genre_count.iloc[0])

print("Lowest Category:")
print(genre_count.index[-1], genre_count.iloc[-1])

Highest Category:
Mystery 512
Lowest Category:
Romance 81

In [76]:
memberco = data_set["Name"].value_counts()
print(memberco)
print("Most frequent member:")
print(memberco.index[0], memberco.iloc[0])

Name
Member 78     31
Member 147    24
Member 122    23
Member 126    23
Member 138    20
              ..
Member 80      6
Member 136     6
Member 29      5
Member 108     5
Member 121     4
Name: count, Length: 150, dtype: int64
Most frequent member:
Member 78 31

In [77]:
publication = data_set.groupby("PublicationYear")["BorrowID"].count()
print(publication)

PublicationYear
1985     40
1986     19
1987     90
1988     20
1989    108
1990     86
1991     48
1992     34
1993     24
1994     62
1995     45
1996     35
1997     48
1998     62
1999     15
2000     59
2001     58
2002     70
2003    102
2004     41
2005     58
2006     44
2007     81
2008     46
2009     12
2010     23
2011     57
2012     30
2013     44
2014     15
2015     40
2016     50
2017     40
2018     46
2019     96
2020     50
2021     38
2022     45
2023     44
2024     24
2025     51
Name: BorrowID, dtype: int64

In [78]:
authors = data_set["Author"].value_counts()

print(authors)
print("Most popular author:")
print(authors.index[0], authors.iloc[0])

Author
Alice Brown          191
David Clark          178
Sarah Mitchell       170
Brandon Sanderson    169
J.K. Rowling         157
Yuval Noah Harari    133
Robert Martin        126
John Smith           121
Maria Green          119
Emily Stone          118
Mark Lee             116
George Orwell        113
Jane Austen          103
Isaac Asimov         103
Agatha Christie       83
Name: count, dtype: int64
Most popular author:
Alice Brown 191

In [79]:
never_borrowed = book[~book["BookID"].isin(borrowings["BookID"])]
never_borrowed

,BookID,Title,Author,Genre,PublicationYear,Publisher,Pages,Language,CopiesAvailable
11,B012,Book 12,J.K. Rowling,Romance,1991,No Starch,404,English,7
12,B013,Book 13,George Orwell,Biography,1995,O'Reilly,483,English,3
14,B015,Book 15,Mark Lee,Romance,1995,No Starch,508,English,4
30,B031,Book 31,Brandon Sanderson,Self Help,1990,Penguin,617,English,1
38,B039,Book 39,Brandon Sanderson,History,2016,HarperCollins,672,English,2
43,B044,Book 44,Brandon Sanderson,Business,2013,HarperCollins,552,English,2
91,B092,Book 92,David Clark,Romance,2004,HarperCollins,323,English,2
124,B125,Book 125,John Smith,Biography,2025,No Starch,276,English,6
128,B129,Book 129,Jane Austen,Self Help,2009,O'Reilly,149,English,7
174,B175,Book 175,Maria Green,History,2017,Pearson,399,English,6
180,B181,Book 181,Sarah Mitchell,Business,2019,No Starch,586,English,5
212,B213,Book 213,Maria Green,Self Help,1999,Pearson,184,English,7
241,B242,Book 242,Isaac Asimov,Biography,1992,No Starch,482,English,6
267,B268,Book 268,Isaac Asimov,Romance,2007,O'Reilly,271,English,3
293,B294,Book 294,Isaac Asimov,Romance,2004,No Starch,318,English,5
297,B298,Book 298,Isaac Asimov,Science Fiction,2018,Penguin,411,English,1
309,B310,Book 310,Jane Austen,Romance,1994,O'Reilly,559,English,0
316,B317,Book 317,Agatha Christie,Biography,2019,O'Reilly,299,English,7
321,B322,Book 322,Yuval Noah Harari,Biography,1988,Pearson,459,English,4
336,B337,Book 337,Maria Green,Business,1992,O'Reilly,386,English,7
343,B344,Book 344,Emily Stone,Business,1993,Random House,208,English,1
347,B348,Book 348,George Orwell,Self Help,1996,HarperCollins,563,English,8
377,B378,Book 378,Robert Martin,Biography,2024,O'Reilly,286,English,6

In [80]:
data_set["BorrowDate"] = pd.to_datetime(data_set["BorrowDate"])
data_set["ReturnDate"] = pd.to_datetime(data_set["ReturnDate"])

In [81]:
data_set["BorrowDuration"] = (data_set["ReturnDate"] - data_set["BorrowDate"]).dt.days

In [82]:
data_set.groupby("Genre")["BorrowDuration"].mean()

Genre
Biography          18.130952
Business           17.190083
Data Science       17.472561
Fantasy            15.813291
History            16.493976
Mystery            16.933594
Programming        17.206780
Romance            16.864198
Science Fiction    17.795181
Self Help          17.536082
Name: BorrowDuration, dtype: float64

In [83]:
book["Genre"].value_counts()

Genre
Business           52
Mystery            43
Data Science       43
Self Help          42
Biography          40
Programming        40
History            39
Science Fiction    35
Romance            34
Fantasy            32
Name: count, dtype: int64

In [84]:
data_set["Month"] = data_set["BorrowDate"].dt.month
monthly = data_set.groupby("Month")["BorrowID"].count()

print(monthly)

Month
1     208
2     193
3     218
4     200
5     204
6     161
7     153
8     142
9     115
10    126
11    147
12    133
Name: BorrowID, dtype: int64

In [85]:
members["MembershipType"].value_counts()

MembershipType
Student    90
Public     30
Faculty    22
Premium     8
Name: count, dtype: int64

In [86]:
book.groupby("Genre")["Pages"].mean()

Genre
Biography          396.000000
Business           427.115385
Data Science       417.232558
Fantasy            412.656250
History            447.974359
Mystery            461.069767
Programming        394.675000
Romance            395.147059
Science Fiction    437.800000
Self Help          425.928571
Name: Pages, dtype: float64

In [87]:
book["Language"].value_counts()

Language
English    400
Name: count, dtype: int64

In [88]:
#Numpy

In [89]:
book_data = book[["Pages", "PublicationYear"]].to_numpy()
print(book_data)

[[ 401 1986]
 [ 678 1991]
 [ 215 1987]
 [ 694 2023]
 [ 579 2011]
 [ 552 1995]
 [ 224 1998]
 [ 390 2007]
 [ 507 2019]
 [ 490 2025]
 [ 353 1987]
 [ 404 1991]
 [ 483 1995]
 [ 295 1989]
 [ 508 1995]
 [ 452 1999]
 [ 394 2005]
 [ 631 2005]
 [ 262 1994]
 [ 558 2019]
 [ 625 1993]
 [ 283 1992]
 [ 599 2009]
 [ 237 1985]
 [ 420 2006]
 [ 389 1985]
 [ 425 2017]
 [ 285 1994]
 [ 451 1985]
 [ 365 2008]
 [ 617 1990]
 [ 606 1993]
 [ 553 2018]
 [ 439 1997]
 [ 582 2013]
 [ 141 1989]
 [ 192 1999]
 [ 192 1987]
 [ 672 2016]
 [ 368 2021]
 [ 219 1997]
 [ 175 2011]
 [ 374 2006]
 [ 552 2013]
 [ 573 2000]
 [ 215 2019]
 [ 338 2016]
 [ 122 1995]
 [ 689 2003]
 [ 179 2003]
 [ 608 1988]
 [ 640 1995]
 [ 189 1989]
 [ 160 2021]
 [ 443 2021]
 [ 525 2000]
 [ 194 2014]
 [ 195 2021]
 [ 477 2001]
 [ 281 2008]
 [ 661 2004]
 [ 226 2004]
 [ 686 1991]
 [ 471 2023]
 [ 377 2017]
 [ 123 2002]
 [ 285 2025]
 [ 234 2020]
 [ 498 2019]
 [ 435 1993]
 [ 375 2007]
 [ 278 2011]
 [ 145 1996]
 [ 374 2011]
 [ 601 2009]
 [ 353 2007]
 [ 405 2010]
 [ 641 2007]
 [ 238 2006]
 [ 231 2001]
 [ 643 2012]
 [ 165 1997]
 [ 321 2019]
 [ 441 2006]
 [ 538 2017]
 [ 316 2020]
 [ 428 1996]
 [ 335 2004]
 [ 449 2023]
 [ 604 1998]
 [ 463 2003]
 [ 323 2004]
 [ 194 2000]
 [ 513 1997]
 [ 125 1994]
 [ 650 1999]
 [ 587 2000]
 [ 444 2018]
 [ 576 2012]
 [ 373 2013]
 [ 364 2016]
 [ 398 2003]
 [ 274 1990]
 [ 544 1998]
 [ 183 2014]
 [ 140 2009]
 [ 519 2007]
 [ 619 2023]
 [ 518 2016]
 [ 250 1995]
 [ 147 2022]
 [ 306 1993]
 [ 585 2005]
 [ 378 2002]
 [ 478 2019]
 [ 373 1987]
 [ 364 2024]
 [ 596 2021]
 [ 237 1995]
 [ 439 2022]
 [ 368 1989]
 [ 699 2023]
 [ 499 2012]
 [ 621 1985]
 [ 276 2025]
 [ 671 2002]
 [ 450 2022]
 [ 369 2002]
 [ 149 2009]
 [ 337 1996]
 [ 402 2006]
 [ 367 1997]
 [ 607 2000]
 [ 346 1990]
 [ 497 2004]
 [ 683 2007]
 [ 377 2002]
 [ 668 2005]
 [ 657 2015]
 [ 489 2003]
 [ 400 2019]
 [ 249 2003]
 [ 600 2021]
 [ 378 1996]
 [ 195 2010]
 [ 207 2021]
 [ 351 2011]
 [ 559 2013]
 [ 221 1988]
 [ 203 2001]
 [ 280 2020]
 [ 418 2023]
 [ 584 2003]
 [ 322 2001]
 [ 272 1999]
 [ 289 1989]
 [ 247 2003]
 [ 632 2010]
 [ 160 1990]
 [ 146 2023]
 [ 395 2022]
 [ 572 2015]
 [ 623 2012]
 [ 448 2011]
 [ 627 2006]
 [ 585 2020]
 [ 533 2005]
 [ 543 2019]
 [ 630 2008]
 [ 682 1998]
 [ 616 2013]
 [ 282 2000]
 [ 215 2020]
 [ 277 2014]
 [ 399 2017]
 [ 587 2015]
 [ 640 1997]
 [ 468 2002]
 [ 425 2003]
 [ 615 2013]
 [ 586 2019]
 [ 512 2000]
 [ 604 1987]
 [ 249 2016]
 [ 222 1991]
 [ 267 1985]
 [ 391 1989]
 [ 666 1990]
 [ 190 2019]
 [ 212 1999]
 [ 426 2013]
 [ 487 1988]
 [ 541 2000]
 [ 511 1990]
 [ 592 1994]
 [ 414 1985]
 [ 426 2013]
 [ 323 2014]
 [ 510 1991]
 [ 525 2003]
 [ 628 1988]
 [ 344 2023]
 [ 219 1993]
 [ 493 1987]
 [ 545 2005]
 [ 663 2019]
 [ 613 1995]
 [ 197 1992]
 [ 494 2010]
 [ 669 1985]
 [ 510 2001]
 [ 694 2015]
 [ 184 1999]
 [ 263 2011]
 [ 219 2016]
 [ 584 1993]
 [ 278 2011]
 [ 537 2016]
 [ 575 1998]
 [ 496 1991]
 [ 402 1988]
 [ 337 1990]
 [ 698 2000]
 [ 341 1998]
 [ 403 2023]
 [ 232 2001]
 [ 451 2007]
 [ 551 1988]
 [ 490 2015]
 [ 346 2013]
 [ 151 2004]
 [ 230 2012]
 [ 449 1989]
 [ 681 2002]
 [ 584 2018]
 [ 237 1991]
 [ 353 2012]
 [ 217 2010]
 [ 276 2001]
 [ 562 1990]
 [ 181 1993]
 [ 482 1992]
 [ 439 2003]
 [ 278 2017]
 [ 496 2007]
 [ 559 2021]
 [ 690 2024]
 [ 399 1986]
 [ 305 2007]
 [ 151 1989]
 [ 549 1998]
 [ 452 2008]
 [ 170 1994]
 [ 572 2012]
 [ 473 2017]
 [ 659 2022]
 [ 176 2010]
 [ 381 1998]
 [ 560 1985]
 [ 355 2019]
 [ 163 1989]
 [ 559 1989]
 [ 534 2003]
 [ 490 2024]
 [ 530 2000]
 [ 467 2004]
 [ 236 1989]
 [ 271 2007]
 [ 297 2001]
 [ 625 1996]
 [ 698 2022]
 [ 189 1994]
 [ 177 2002]
 [ 582 2004]
 [ 212 2003]
 [ 162 2022]
 [ 607 1997]
 [ 471 2013]
 [ 568 1987]
 [ 492 2024]
 [ 466 2009]
 [ 216 1989]
 [ 273 2003]
 [ 437 1994]
 [ 692 1990]
 [ 659 1993]
 [ 138 2017]
 [ 617 1998]
 [ 422 1994]
 [ 464 2018]
 [ 305 1994]
 [ 493 1987]
 [ 579 2003]
 [ 318 2004]
 [ 408 2013]
 [ 324 2011]
 [ 612 1988]
 [ 411 2018]
 [ 645 2002]
 [ 581 1990]
 [ 525 2011]
 [ 503 2009]
 [ 463 1991]
 [ 262 2003]
 [ 139 1985]
 [ 660 2020]
 [ 244 2000]
 [ 588 2025]
 [ 136 2023]
 [ 559 1994]
 [ 546 2000]
 [ 189 2018]
 [ 140 2017]
 [ 516 1987]
 [ 473 2007]
 [ 460 2022]
 [ 299 2019]
 [ 258 2025]
 [ 326 1987]
 [ 437 1987]
 [ 157 2015]
 [ 459 1988]
 [ 570 2012]
 [ 629 2016]
 [ 554 2002]
 [ 420 1996]
 [ 422 2005]
 [ 574 2012]
 [ 565 2007]
 [ 535 1989]
 [ 568 1986]
 [ 495 2000]
 [ 277 1987]
 [ 260 2013]
 [ 405 2005]
 [ 650 1996]
 [ 386 1992]
 [ 622 2003]
 [ 296 1989]
 [ 186 2007]
 [ 298 2004]
 [ 262 1992]
 [ 687 1986]
 [ 208 1993]
 [ 540 2015]
 [ 444 1989]
 [ 251 2018]
 [ 563 1996]
 [ 276 1992]
 [ 350 2005]
 [ 321 1990]
 [ 666 2025]
 [ 277 2022]
 [ 697 2023]
 [ 391 1990]
 [ 151 2011]
 [ 429 2003]
 [ 194 2004]
 [ 595 2011]
 [ 446 1994]
 [ 695 2008]
 [ 393 2014]
 [ 417 1991]
 [ 283 2011]
 [ 283 2005]
 [ 629 2016]
 [ 366 2017]
 [ 408 1988]
 [ 128 2003]
 [ 494 2001]
 [ 695 2010]
 [ 515 2003]
 [ 241 2002]
 [ 691 2008]
 [ 641 1997]
 [ 260 1987]
 [ 272 2018]
 [ 286 2024]
 [ 639 2022]
 [ 606 2021]
 [ 435 1992]
 [ 353 2001]
 [ 509 1995]
 [ 232 1987]
 [ 275 2005]
 [ 602 2011]
 [ 694 2018]
 [ 441 2018]
 [ 482 2006]
 [ 405 1997]
 [ 332 2004]
 [ 400 2007]
 [ 524 2019]
 [ 414 2003]
 [ 610 2001]
 [ 398 2002]
 [ 368 2022]
 [ 358 1999]
 [ 603 2006]
 [ 281 1985]]

In [90]:
pages = book["Pages"].to_numpy()

In [91]:
print(pages.max())
print(pages.min())

699
122

In [92]:
duration = data_set["BorrowDuration"].to_numpy()
result = duration[duration > 10]

print(result)

[25 17 13 ... 22 18 18]

In [93]:
sorted_pages = np.sort(pages)
print(sorted_pages)

[122 123 125 128 136 138 139 140 140 141 145 146 147 149 151 151 151 157
 160 160 162 163 165 170 175 176 177 179 181 183 184 186 189 189 189 190
 192 192 194 194 194 195 195 197 203 207 208 212 212 215 215 215 216 217
 219 219 219 221 222 224 226 230 231 232 232 234 236 237 237 237 238 241
 244 247 249 249 250 251 258 260 260 262 262 262 263 267 271 272 272 273
 274 275 276 276 276 277 277 277 278 278 278 280 281 281 282 283 283 283
 285 285 286 289 295 296 297 298 299 305 305 306 316 318 321 321 322 323
 323 324 326 332 335 337 337 338 341 344 346 346 350 351 353 353 353 353
 355 358 364 364 365 366 367 368 368 368 369 373 373 374 374 375 377 377
 378 378 381 386 389 390 391 391 393 394 395 398 398 399 399 400 400 401
 402 402 403 404 405 405 405 408 408 411 414 414 417 418 420 420 422 422
 425 425 426 426 428 429 435 435 437 437 439 439 439 441 441 443 444 444
 446 448 449 449 450 451 451 452 452 459 460 463 463 464 466 467 468 471
 471 473 473 477 478 482 482 483 487 489 490 490 490 492 493 493 494 494
 495 496 496 497 498 499 503 507 508 509 510 510 511 512 513 515 516 518
 519 524 525 525 525 530 533 534 535 537 538 540 541 543 544 545 546 549
 551 552 552 553 554 558 559 559 559 559 560 562 563 565 568 568 570 572
 572 573 574 575 576 579 579 581 582 582 584 584 584 585 585 586 587 587
 588 592 595 596 599 600 601 602 603 604 604 606 606 607 607 608 610 612
 613 615 616 617 617 619 621 622 623 625 625 627 628 629 629 630 631 632
 639 640 640 641 641 643 645 650 650 657 659 659 660 661 663 666 666 668
 669 671 672 678 681 682 683 686 687 689 690 691 692 694 694 694 695 695
 697 698 698 699]

In [94]:
ages = members["Age"].to_numpy()
add_year = ages + 1

print(add_year)

[48 48 44 66 23 41 22 21 30 65 43 43 61 41 53 27 67 48 43 48 36 21 68 32
 57 57 66 47 32 51 71 57 38 52 38 54 62 50 60 39 28 30 33 70 54 54 34 40
 42 65 36 57 31 32 19 66 34 34 43 60 35 50 70 32 45 33 35 28 33 34 60 67
 66 29 27 53 21 22 27 64 32 22 50 53 20 37 71 25 28 58 36 42 55 38 60 44
 54 59 24 60 25 32 21 53 39 56 23 55 43 67 51 25 23 68 20 50 54 30 68 64
 36 64 39 24 47 25 30 54 20 54 57 19 43 34 29 38 28 46 38 42 65 58 25 19
 58 47 71 39 39 39]

In [95]:
#Final Summary

In [96]:
#Most popular author:Alice Brown
#Probability in History book: 0.04
#Probability of History Fiction book borrowed by a public member: 0.00
#Most frequent member: Member 78
#Observation: Mystery has the highest number of borrowings, whereas Romance has the lowest
#Mystery books have the highest average page count (461), while programming and romance books are the shortest on average (394-395 pages)